spring:
  redis:
    url: ${REDIS_URL}
    password: ${REDIS_TOKEN}

  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB}
      auto-index-creation: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${PORT:8080}
  servlet:
    context-path: /journalApp

app:
  redis:
    ttl: ${REDIS_TTL}
